version: "3.9"
services:
  frontend:
    container_name: lynx-frontend
    build:
      context: .
      target: dev
    volumes:
      - ./frontend/:/frontend/
      - /frontend/node_modules
    ports:
      - "3000:3000"
  backend:
    container_name: lynx-backend
    build:
      context: .
      target: backend
      args:
        - dev=true
    volumes:
      - ./backend/:/backend/
    ports:
      - "5001:5001"
